# Generated by Django 4.2.1 on 2023-05-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_master_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='фото мастера'),
        ),
        migrations.AddField(
            model_name='master',
            name='specialization',
            field=models.CharField(blank=True, max_length=200, verbose_name='специализация'),
        ),
        migrations.AddField(
            model_name='salon',
            name='schedule',
            field=models.CharField(blank=True, max_length=50, verbose_name='график работы'),
        ),
    ]
