# Generated by Django 4.2.1 on 2023-05-27 10:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя клиента')),
                ('phonenumber', phonenumber_field.modelfields.PhoneNumberField(db_index=True, max_length=128, region=None, verbose_name='Номер клиента')),
                ('score', models.IntegerField(blank=True, db_index=True, verbose_name='Количество баллов салона')),
                ('registered_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Время отзыва')),
                ('visited_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата посещения салона')),
                ('text', models.TextField(blank=True, verbose_name='Текст отзыва')),
                ('master', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='shop.master', verbose_name='Мастер, на которого оставили отзыв')),
                ('salon', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='shop.salon', verbose_name='Салон, на который оставили отзыв')),
            ],
            options={
                'verbose_name': 'Отзыв на салон',
                'verbose_name_plural': 'Отзывы на салон',
                'ordering': ('-registered_at',),
            },
        ),
    ]
