# Generated by Django 4.2.1 on 2023-05-29 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='shop.master', verbose_name='Мастер, на которого оставили отзыв'),
        ),
        migrations.AlterField(
            model_name='review',
            name='salon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='shop.salon', verbose_name='Салон, на который оставили отзыв'),
        ),
    ]
